# Generated by Django 4.2 on 2023-11-30 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=255)),
                ('atividade', models.CharField(max_length=255)),
                ('carga_horaria', models.IntegerField()),
                ('avaliacao_red', models.IntegerField()),
                ('avaliacao_yellow', models.IntegerField()),
                ('avaliacao_green', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Crianca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outro', 'Outro')], max_length=10)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('rg', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=100)),
                ('historico_medico', models.FileField(upload_to='historicos/')),
                ('autorizacao_responsavel', models.FileField(upload_to='autorizacoes/')),
                ('foto', models.FileField(upload_to='fotocrianca/')),
                ('naturalidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('identidade', models.CharField(max_length=20)),
                ('dt_expedicao_ident', models.DateField()),
                ('orgao_expeditor', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=100)),
                ('cep', models.IntegerField()),
                ('raca', models.CharField(choices=[('Preto', 'Preto'), ('Branca', 'Branca'), ('Parda', 'Parda'), ('Amarela', 'Amarela'), ('Outra', 'Outra')], max_length=50)),
                ('telefone_responsavel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DadosCrianca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=255)),
                ('atividade', models.CharField(max_length=255)),
                ('carga_horaria', models.CharField(max_length=255)),
                ('desempenho', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackPadrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('destinatario', models.TextField(choices=[('Afilhado', 'Afilhado'), ('Gotas de Flor', 'Gotas')])),
                ('mensagem', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Padrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=12)),
                ('endereco', models.CharField(max_length=500)),
                ('cpf', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('rg', models.CharField(max_length=10)),
                ('profissao', models.CharField(max_length=40)),
                ('reason', models.CharField(max_length=1000)),
                ('senha', models.CharField(default='12345678', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Recordacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_recordacao', models.ImageField(upload_to='recordacoes_imagens/')),
                ('data', models.DateField(auto_now=True, verbose_name='Data')),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_bloom.crianca')),
            ],
        ),
        migrations.CreateModel(
            name='ChildActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(choices=[('janeiro', 'Janeiro'), ('Fevereiro', 'Fevereiro'), ('marco', 'Março'), ('abril', 'Abril'), ('maio', 'Maio'), ('junho', 'Junho'), ('julho', 'Julho'), ('agosto', 'Agosto'), ('setembro', 'Setembro'), ('outubro', 'Outubro'), ('novembro', 'Novembro'), ('dezembro', 'Dezembro')], max_length=20)),
                ('atividade_secao1', models.CharField(choices=[('capoeira', 'Capoeira'), ('coral', 'Coral'), ('volei', 'Vôlei'), ('futebol', 'Futebol'), ('artes', 'Artes'), ('yoga', 'Yoga'), ('meioambiente', 'Meio Ambiente'), ('cidadania', 'Cidadania')], max_length=20)),
                ('carga', models.CharField(max_length=50)),
                ('desempenho_secao1', models.CharField(choices=[('otimo', 'Ótimo'), ('regular', 'Regular'), ('ruim', 'Ruim')], max_length=20)),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_bloom.crianca')),
            ],
        ),
    ]
