# Generated by Django 4.2 on 2023-11-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bloom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crianca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outro', 'Outro')], max_length=10)),
                ('cpf', models.CharField(max_length=11)),
                ('rg', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=100)),
                ('historico_medico', models.FileField(upload_to='historicos/')),
                ('autorizacao_responsavel', models.FileField(upload_to='autorizacoes/')),
            ],
        ),
        migrations.CreateModel(
            name='Padrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=12)),
                ('endereco', models.CharField(max_length=500)),
                ('cpf', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('rg', models.CharField(max_length=10)),
                ('profissao', models.CharField(max_length=40)),
                ('reason', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Pirralho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='feedbackpadrinho',
            name='destinatario',
            field=models.TextField(choices=[('Afilhado', 'Afilhado'), ('Gotas de Flor', 'Gotas')]),
        ),
        migrations.AlterField(
            model_name='feedbackpadrinho',
            name='mensagem',
            field=models.CharField(max_length=1000),
        ),
    ]
