# Generated by Django 4.2 on 2023-11-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bloom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=40)),
                ('cpf', models.IntegerField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=30)),
                ('user', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Padrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf', models.IntegerField(max_length=11, unique=True)),
                ('endereco', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=30)),
                ('senha', models.CharField(max_length=30)),
            ],
        ),
    ]
