# Generated by Django 4.2 on 2023-11-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bloom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crianca',
            name='raca',
            field=models.CharField(choices=[('Preto', 'Preto'), ('Branca', 'Branca'), ('Parda', 'Parda'), ('Amarela', 'Amarela'), ('Outra', 'Outra')], max_length=50),
        ),
    ]
