# Generated by Django 4.2 on 2023-11-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bloom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackPadrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.TextField(choices=[('Afilhado', 'Afilhado'), ('Gotas de Flor', 'Gotas')])),
                ('mensagem', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Padrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.IntegerField()),
                ('endereco', models.CharField(max_length=500)),
                ('cpf', models.IntegerField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('rg', models.IntegerField(max_length=9)),
                ('profissao', models.CharField(max_length=40)),
                ('reason', models.CharField(max_length=1000)),
                ('senha', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='crianca',
            name='autorizacao_responsavel',
        ),
        migrations.RemoveField(
            model_name='crianca',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='crianca',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='crianca',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='crianca',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='crianca',
            name='historico_medico',
        ),
        migrations.RemoveField(
            model_name='crianca',
            name='rg',
        ),
        migrations.AddField(
            model_name='crianca',
            name='idade',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
