# Generated by Django 4.2 on 2023-11-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bloom', '0002_funcionario_padrinho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='padrinho',
            name='cpf',
            field=models.IntegerField(unique=True),
        ),
    ]
