# Generated by Django 4.2 on 2023-11-22 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bloom', '0003_alter_funcionario_cpf_alter_padrinho_cpf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='senha',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='padrinho',
            old_name='senha',
            new_name='password',
        ),
    ]
