# Generated by Django 4.2 on 2023-11-29 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_bloom', '0003_padrinho_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crianca',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.CreateModel(
            name='Recordacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_recordacao', models.ImageField(upload_to='recordacoes_imagens/')),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_bloom.crianca')),
            ],
        ),
    ]
