# Generated by Django 4.2 on 2023-11-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bloom', '0004_alter_crianca_cpf_recordacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordacoes',
            name='data',
            field=models.DateField(auto_now=True, verbose_name='Data'),
        ),
    ]
