# Generated by Django 4.2 on 2023-11-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bloom', '0004_login_pirralho_remove_padrinho_senha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crianca',
            name='data_nascimento',
            field=models.IntegerField(),
        ),
    ]
