# Generated by Django 4.2 on 2023-11-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bloom', '0005_recordacoes_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=255)),
                ('atividade', models.CharField(max_length=255)),
                ('carga_horaria', models.IntegerField()),
                ('avaliacao_red', models.IntegerField()),
                ('avaliacao_yellow', models.IntegerField()),
                ('avaliacao_green', models.IntegerField()),
            ],
        ),
    ]
