# Generated by Django 4.2 on 2023-11-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bloom', '0005_alter_crianca_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crianca',
            name='autorizacao_responsavel',
            field=models.FileField(default=None, upload_to='autorizacoes/'),
        ),
    ]
