# Generated by Django 4.2 on 2023-11-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bloom', '0006_alter_crianca_autorizacao_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crianca',
            name='autorizacao_responsavel',
            field=models.FileField(default='str', upload_to='autorizacoes/'),
        ),
    ]
