# Generated by Django 4.2 on 2023-11-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bloom', '0007_alter_crianca_autorizacao_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crianca',
            name='autorizacao_responsavel',
            field=models.FileField(default='static/arquives/PDF-teste.pdf', upload_to='autorizacoes/'),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='historico_medico',
            field=models.FileField(default='static/arquives/PDF-teste.pdf', upload_to='historicos/'),
        ),
    ]
