# Generated by Django 4.2 on 2023-11-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bloom', '0008_alter_crianca_autorizacao_responsavel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crianca',
            name='data_nascimento',
            field=models.DateField(),
        ),
    ]
