# Generated by Django 4.2 on 2023-11-27 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bloom', '0010_auto_20231127_1828'),
    ]

    operations = [
    ]
