# Generated by Django 4.2 on 2023-11-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bloom', '0011_auto_20231127_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crianca',
            name='data_nascimento',
            field=models.CharField(max_length=10),
        ),
    ]
